services:
  postgres:
    image: postgres:17-alpine
    container_name: sentinelops-postgres
    environment:
      POSTGRES_DB: sentinelops
      POSTGRES_USER: sentinelops
      POSTGRES_PASSWORD: sentinelops
    ports: ["5433:5432"]
    volumes: ["sentinelops_pgdata:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentinelops -d sentinelops"]
      interval: 5s
      timeout: 3s
      retries: 10
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: sentinelops-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy

  grafana:
    image: grafana/grafana:12.2.0
    container_name: sentinelops-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: sentinelops
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3000:3000"
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus


  loki:
    image: grafana/loki:3.5.5
    container_name: sentinelops-loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./observability/loki/loki.yml:/etc/loki/local-config.yaml:ro
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:3.5.5
    container_name: sentinelops-promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./observability/promtail/promtail.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki

volumes:
  sentinelops_pgdata:
